import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/app/Component/Header";

import Marquee from "@/app/Component/Marquee";

const notoSerifBengali = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      
      className={`${notoSerifBengali.className} bg-[#F0F5F0] h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        <Marquee />
        <main>{children}</main>
        </body>
    </html>
  );
}
